export type OptYearMetadata = {
  tahun: number;
  rowCount: number;
  bucket?: string;
  storagePath?: string;
  fileName: string;
  publicUrl: string;
  fileSizeBytes: number;
  sourceFile?: string;
  updatedAt: string;
};

export type OptReportRow = {
  id: string;
  sourceRowNumber: number;
  tahun: number;
  bulan: number;
  periode: number;
  mt: string;
  kabupaten: string;
  kecamatan: string;
  desa: string;
  latitude: number;
  longitude: number;
  komoditas: string;
  lt: number;
  opt: string;
  ssr: number;
  sss: number;
  ssb: number;
  ssp: number;
  ssj: number;
  terkendali: number;
  panen: number;
  intensitas: number;
  ltsr: number;
  ltss: number;
  ltsb: number;
  ltsp: number;
  ltsj: number;
  kimia: number;
  hayati: number;
  eradikasi: number;
  cl: number;
  jumlahPengendali: number;
  lksr: number;
  lkss: number;
  lksb: number;
  lksp: number;
  lksj: number;
  waspada: number;
};
